package com.dilshad.myapplication.domain.rag

data class CurriculumChunk(
    val id: String,
    val board: String,
    val classLevel: String,
    val subject: String,
    val chapter: String,
    val section: String,
    val topic: String,
    val conceptId: String,
    val content: String,
    val sourceCitation: String,
    val keyFormula: String = "",
    val realWorldExample: String = "",
    val keywords: List<String> = emptyList(),
    val hindiSummary: String = "",
    val odiaSummary: String = ""
)

object CurriculumCorpus {
    val chunks = listOf(
        // Chapter 1: Light - Reflection and Refraction
        CurriculumChunk(
            id = "cbse_10_sci_ch10_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Light - Reflection and Refraction",
            section = "10.1 Reflection of Light",
            topic = "Laws of Reflection",
            conceptId = "concept_reflection",
            content = "Light is a form of electromagnetic radiation that enables vision and travels in rectilinear paths (straight lines). Laws of Reflection: 1) The angle of incidence (i) is equal to the angle of reflection (r): ∠i = ∠r. 2) The incident ray, the reflected ray, and the normal to the mirror at the point of incidence all lie in the same plane. A plane mirror always forms a virtual, erect image located at the same distance behind the mirror as the object is in front, with magnification m = +1, laterally inverted.",
            sourceCitation = "CBSE Science Class 10 Chapter 10 Section 10.1",
            keyFormula = "∠i = ∠r  •  m = +1 (plane mirror)",
            realWorldExample = "Viewing yourself in a flat bathroom mirror; looking at car headlamp reflectors.",
            keywords = listOf("reflection", "angle", "incidence", "normal", "plane mirror", "lateral inversion", "virtual image"),
            hindiSummary = "प्रकाश का परावर्तन: आपतन कोण परावर्तन कोण के बराबर होता है (∠i = ∠r)। समतल दर्पण हमेशा आभासी और सीधा प्रतिबिम्ब बनाता है।",
            odiaSummary = "ଆଲୋକର ପ୍ରତିଫଳନ: ଆପତନ କୋଣ ପ୍ରତିଫଳନ କୋଣ ସହ ସମାନ (∠i = ∠r)। ସମତଳ ଦର୍ପଣ କାଳ୍ପନିକ ଓ ସଳଖ ପ୍ରତିବିମ୍ବ ଗଠନ କରେ।"
        ),
        CurriculumChunk(
            id = "cbse_10_sci_ch10_02",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Light - Reflection and Refraction",
            section = "10.2 Spherical Mirrors",
            topic = "Mirror Formula and Magnification",
            conceptId = "concept_mirror_formula",
            content = "Spherical mirrors have curved reflecting surfaces: Concave (converging inward) and Convex (diverging outward). New Cartesian Sign Convention: Object is always placed to the left (u is negative). Focal length f of a concave mirror is negative; for a convex mirror, f is positive. Mirror Formula: 1/f = 1/v + 1/u. Linear Magnification: m = h'/h = -v/u. If m is negative, the image is real and inverted. If m is positive, the image is virtual and erect. Convex mirrors always produce virtual, erect, and diminished images, providing a wider field of view.",
            sourceCitation = "CBSE Science Class 10 Chapter 10 Section 10.2",
            keyFormula = "1/f = 1/v + 1/u  •  m = -v/u = h'/h  •  R = 2f",
            realWorldExample = "Dentist mirrors and car headlights (concave); rear-view wing mirrors of cars (convex).",
            keywords = listOf("mirror", "concave", "convex", "focal length", "magnification", "rear-view", "radius of curvature", "sign convention"),
            hindiSummary = "गोलीय दर्पण सूत्र: 1/f = 1/v + 1/u और आवर्धन m = -v/u। अवतल दर्पण अभिसारी होता है और उत्तल दर्पण अपसारी।",
            odiaSummary = "ଗୋଲକୀୟ ଦର୍ପଣ ସୂତ୍ର: 1/f = 1/v + 1/u ଏବଂ ପରିବର୍ଦ୍ଧନ m = -v/u। ଅବତଳ ଦର୍ପଣ ଅଭିସାରୀ ଏବଂ ଉତ୍ତଳ ଦର୍ପଣ ଅପସାରୀ।"
        ),
        CurriculumChunk(
            id = "cbse_10_sci_ch10_03",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Light - Reflection and Refraction",
            section = "10.3 Refraction of Light",
            topic = "Refraction and Snell's Law",
            conceptId = "concept_refraction",
            content = "Refraction is the change in direction (bending) of a light ray when passing obliquely from one transparent medium into another, caused by the change in the speed of light. When traveling from an optically rarer medium (air) to an optically denser medium (glass/water), light bends towards the normal line. When traveling from denser to rarer, light bends away from the normal. Snell's Law states: sin(i) / sin(r) = constant = n21, where n21 is the refractive index of medium 2 with respect to medium 1. Absolute refractive index n = c / v (speed of light in vacuum c = 3 × 10^8 m/s divided by speed in medium v).",
            sourceCitation = "CBSE Science Class 10 Chapter 10 Section 10.3",
            keyFormula = "Snell's Law: n = sin(i) / sin(r)  •  n = c / v  •  n21 = v1 / v2",
            realWorldExample = "A pencil appearing bent at the water surface; swimming pool floor appearing shallower than actual depth.",
            keywords = listOf("refraction", "snell", "refractive index", "speed of light", "rarer", "denser", "bent pencil", "normal", "optical density"),
            hindiSummary = "प्रकाश का अपवर्तन: एक माध्यम से दूसरे में जाने पर प्रकाश की गति बदलने से मुड़ना। स्नेल का नियम: sin(i)/sin(r) = n।",
            odiaSummary = "ଆଲୋକର ପ୍ରତିସରଣ: ମାଧ୍ୟମ ପରିବର୍ତ୍ତନ ହେଲେ ଆଲୋକର ବେଗ ବଦଳି ବଙ୍କିବା। ସ୍ନେଲଙ୍କ ନିୟମ: sin(i)/sin(r) = n।"
        ),
        CurriculumChunk(
            id = "cbse_10_sci_ch10_04",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Light - Reflection and Refraction",
            section = "10.4 Refraction by Spherical Lenses",
            topic = "Lens Formula and Power of Lens",
            conceptId = "concept_lens_formula",
            content = "A lens is a transparent optical material bounded by two surfaces, of which at least one is spherical. Convex lenses are thicker in the middle and converge light rays (focal length f is positive). Concave lenses are thinner in the middle and diverge light rays (focal length f is negative). Lens Formula: 1/f = 1/v - 1/u. Magnification: m = h'/h = +v/u. Power of a Lens (P): P = 1 / f (where f must be in metres), expressed in Dioptres (D). Convex lens has positive power (+D); concave lens has negative power (-D). Total power for lenses in contact: P = P1 + P2 + ...",
            sourceCitation = "CBSE Science Class 10 Chapter 10 Section 10.4",
            keyFormula = "1/f = 1/v - 1/u  •  m = +v/u = h'/h  •  P = 1/f (in meters)",
            realWorldExample = "Magnifying glasses (convex); spectacles for myopia/hypermetropia correction; microscope objectives.",
            keywords = listOf("lens", "convex", "concave", "lens formula", "power", "dioptre", "diopter", "converging", "diverging", "magnification"),
            hindiSummary = "लेंस सूत्र: 1/f = 1/v - 1/u। लेंस की क्षमता P = 1/f (मीटर में), मात्रक डायोप्टर (D) है। उत्तल लेंस धनात्मक और अवतल ऋणात्मक।",
            odiaSummary = "ଲେନ୍ସ ସୂତ୍ର: 1/f = 1/v - 1/u। ଲେନ୍ସର କ୍ଷମତା P = 1/f (ମିଟରରେ), ଏକକ ଡାୟୋପ୍ଟର (D)। ଉତ୍ତଳ ଲେନ୍ସ ଯୁକ୍ତାତ୍ମକ ଓ ଅବତଳ ବିୟୁକ୍ତାତ୍ମକ।"
        ),

        // Chapter 2: The Human Eye and the Colourful World
        CurriculumChunk(
            id = "cbse_10_sci_ch11_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "The Human Eye and the Colourful World",
            section = "11.1 The Human Eye and Vision Defects",
            topic = "Myopia, Hypermetropia, and Presbyopia",
            conceptId = "concept_eye_defects",
            content = "The human eye works like a camera, using an adjustable crystalline convex lens controlled by ciliary muscles (power of accommodation). The retina contains photoreceptor rods and cones. Near point for normal eye is 25 cm; far point is infinity. Defects of Vision: 1) Myopia (near-sightedness): nearby objects clear, distant objects blurred. Image formed in front of retina due to excessive curvature of eye lens or elongated eyeball. Corrected by a Concave Lens of suitable focal length. 2) Hypermetropia (far-sightedness): distant objects clear, close objects blurred. Image formed behind retina due to too long focal length or shortened eyeball. Corrected by a Convex Lens. 3) Presbyopia: aging eye loses elasticity; corrected by bifocal lenses.",
            sourceCitation = "CBSE Science Class 10 Chapter 11 Section 11.1",
            keyFormula = "Near point = 25 cm  •  Far point = ∞  •  Myopia: concave (-D)  •  Hypermetropia: convex (+D)",
            realWorldExample = "Students unable to read blackboard (myopia); adults needing reading glasses to read newspapers (presbyopia/hypermetropia).",
            keywords = listOf("eye", "myopia", "hypermetropia", "presbyopia", "retina", "ciliary muscles", "accommodation", "near point", "concave lens", "convex lens"),
            hindiSummary = "नेत्र दोष: निकट-दृष्टि दोष (मायोपिया) को अवतल लेंस से और दूर-दृष्टि दोष (हाइपरमेट्रोपिया) को उत्तल लेंस से ठीक किया जाता है।",
            odiaSummary = "ଦୃଷ୍ଟି ଦୋଷ: ମାୟୋପିଆ (ନିକଟ ଦୃଷ୍ଟି) ଅବତଳ ଲେନ୍ସ ଦ୍ୱାରା ଏବଂ ହାଇପରମେଟ୍ରୋପିଆ ଉତ୍ତଳ ଲେନ୍ସ ଦ୍ୱାରା ସଂଶୋଧନ କରାଯାଏ।"
        ),
        CurriculumChunk(
            id = "cbse_10_sci_ch11_02",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "The Human Eye and the Colourful World",
            section = "11.2 Dispersion and Atmospheric Refraction",
            topic = "Prism Dispersion, Rainbows, and Atmospheric Refraction",
            conceptId = "concept_dispersion",
            content = "Dispersion: When white light passes through a triangular glass prism, it splits into its component spectrum of seven colors (VIBGYOR: Violet, Indigo, Blue, Green, Yellow, Orange, Red) because each color travels at a different speed in glass and refracts through different angles (Red bends least, Violet bends most). A rainbow is an internal reflection and dispersion of sunlight through spherical raindrops. Atmospheric Refraction: Layers of Earth's atmosphere have varying optical densities and temperatures. This causes: 1) Twinkling of stars (continuous shifting of apparent position). 2) Advanced sunrise (2 minutes early) and delayed sunset (2 minutes late). 3) Flattened appearance of the Sun at horizon.",
            sourceCitation = "CBSE Science Class 10 Chapter 11 Section 11.2",
            keyFormula = "VIBGYOR (Violet bends most, Red bends least)  •  Atmospheric time shift = 4 minutes daily",
            realWorldExample = "Rainbow in the sky after rain; stars twinkling at night while planets do not; early sunrise.",
            keywords = listOf("prism", "dispersion", "spectrum", "vibgyor", "rainbow", "atmospheric refraction", "twinkling stars", "advanced sunrise"),
            hindiSummary = "वर्ण विक्षेपण और वायुमंडलीय अपवर्तन: श्वेत प्रकाश का सात रंगों में बंटना। तारों का टिमटिमाना वायुमंडलीय अपवर्तन का परिणाम है।",
            odiaSummary = "ବର୍ଣ୍ଣ ବିଚ୍ଛୁରଣ ଓ ବାୟୁମଣ୍ଡଳୀୟ ପ୍ରତିସରଣ: ଧଳା ଆଲୋକ ସାତୋଟି ରଙ୍ଗରେ ବିଭାଜିତ ହେବା। ତାରାମାନଙ୍କ ଝଲକିବା ବାୟୁମଣ୍ଡଳୀୟ ପ୍ରତିସରଣ ଯୋଗୁଁ ହୁଏ।"
        ),
        CurriculumChunk(
            id = "cbse_10_sci_ch11_03",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "The Human Eye and the Colourful World",
            section = "11.3 Scattering of Light",
            topic = "Tyndall Effect and Blue Sky",
            conceptId = "concept_scattering",
            content = "Scattering of light occurs when light collides with fine particles in a colloidal medium and spreads in all directions. The Tyndall Effect is the visibility of a light beam path through a colloidal suspension, smoke, or dense forest mist. Rayleigh Scattering Law: Intensity of scattered light is inversely proportional to the 4th power of wavelength (I ∝ 1/λ^4). Because blue light has a much shorter wavelength than red light, it is scattered almost 16 times more strongly by nitrogen and oxygen molecules in the upper atmosphere. Hence, the sky appears blue. At sunrise and sunset, light travels a longer atmospheric path, scattering away blue light and leaving primarily the longer red wavelengths to reach our eyes.",
            sourceCitation = "CBSE Science Class 10 Chapter 11 Section 11.3",
            keyFormula = "Rayleigh Scattering: I ∝ 1 / λ^4  (λ_red > λ_blue)",
            realWorldExample = "Blue clear sky; red color of setting sun; sunbeam visible through smoke in a dusty dark room (Tyndall effect).",
            keywords = listOf("scattering", "tyndall effect", "blue sky", "red sunset", "wavelength", "rayleigh", "colloid"),
            hindiSummary = "प्रकाश का प्रकीर्णन: नीले प्रकाश का तरंगदैर्घ्य छोटा होने के कारण यह अधिक प्रकीर्णित होता है, जिससे आकाश नीला दिखाई देता है।",
            odiaSummary = "ଆଲୋକର ବିକିରଣ: ନୀଳ ଆଲୋକର ତରଙ୍ଗ ଦୈର୍ଘ୍ୟ କମ ଥିବାରୁ ଏହା ଅଧିକ ବିକିରିତ ହୋଇ ଆକାଶ ନୀଳ ଦେଖାଯାଏ।"
        ),

        // Chapter 3: Electricity
        CurriculumChunk(
            id = "cbse_10_sci_ch12_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Electricity",
            section = "12.1 Electric Current and Ohm's Law",
            topic = "Electric Current, Potential Difference, and Ohm's Law",
            conceptId = "concept_electricity_ohms_law",
            content = "Electric current (I) is the rate of flow of electric charges: I = Q / t (measured in Amperes, A; 1 A = 1 C/s). Potential difference (V) between two points is the work done (W) to move a unit positive charge (Q): V = W / Q (measured in Volts, V; 1 V = 1 J/C). Ohm's Law states that at constant temperature, the current flowing through a metallic conductor is directly proportional to the potential difference across its terminals: V ∝ I, or V = I * R, where R is the electrical resistance (measured in Ohms, Ω). Resistance depends on conductor length (R ∝ L), cross-sectional area (R ∝ 1/A), and material resistivity (ρ): R = ρ * L / A.",
            sourceCitation = "CBSE Science Class 10 Chapter 12 Section 12.1",
            keyFormula = "I = Q / t  •  V = W / Q  •  Ohm's Law: V = I * R  •  R = ρ * L / A",
            realWorldExample = "Electric current in phone chargers, heating coils, copper wiring in household electricity.",
            keywords = listOf("electricity", "current", "voltage", "potential difference", "resistance", "ohms law", "ampere", "volt", "resistivity"),
            hindiSummary = "ओम का नियम: नियत ताप पर विभवान्तर धारा के समानुपाती होता है (V = I * R)। धारा I = Q/t, विभवान्तर V = W/Q।",
            odiaSummary = "ଓମ୍‌ଙ୍କ ନିୟମ: ସ୍ଥିର ତାପମାତ୍ରାରେ ବିଦ୍ୟୁତ ବିଭବାନ୍ତର ବିଦ୍ୟୁତ ସ୍ରୋତ ସହ ସମାନୁପାତୀ (V = I * R)।"
        ),
        CurriculumChunk(
            id = "cbse_10_sci_ch12_02",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Electricity",
            section = "12.2 Combination of Resistors and Electric Circuits",
            topic = "Series and Parallel Combinations",
            conceptId = "concept_circuits",
            content = "Series Combination: Resistors connected end-to-end. Current I is identical through every resistor; total voltage V = V1 + V2 + ... Equivalent resistance is the direct algebraic sum: Rs = R1 + R2 + R3. The equivalent resistance is always greater than the highest individual resistance. Disadvantage: if one component fails, the entire circuit opens. Parallel Combination: Resistors connected across the same common nodes. Voltage V is identical across each branch; total current I = I1 + I2 + ... Equivalent resistance formula: 1/Rp = 1/R1 + 1/R2 + 1/R3. For two resistors: Rp = (R1 * R2) / (R1 + R2). The equivalent resistance is always smaller than the smallest individual resistor. Domestic circuits always use parallel wiring.",
            sourceCitation = "CBSE Science Class 10 Chapter 12 Section 12.2",
            keyFormula = "Series: Rs = R1 + R2 + R3  •  Parallel: 1/Rp = 1/R1 + 1/R2 + 1/R3  •  Two Resistors: Rp = (R1*R2)/(R1+R2)",
            realWorldExample = "Holiday fairy lights in series; home appliances (lights, fans, refrigerator) connected in parallel so each operates independently at 220V.",
            keywords = listOf("series", "parallel", "resistors", "equivalent resistance", "circuits", "household wiring"),
            hindiSummary = "प्रतिरोधकों का संयोजन: श्रेणीक्रम में Rs = R1 + R2, समांतर क्रम में 1/Rp = 1/R1 + 1/R2। घरेलू उपकरण समांतर क्रम में जुड़े होते हैं।",
            odiaSummary = "ପ୍ରତିରୋଧକ ମିଶ୍ରଣ: ପଂକ୍ତି ସଂଯୋଗରେ Rs = R1 + R2, ସମାନ୍ତର ସଂଯୋଗରେ 1/Rp = 1/R1 + 1/R2। ଘରୋଇ ତାର ସମାନ୍ତର ଭାବେ ସଂଯୁକ୍ତ।"
        ),
        CurriculumChunk(
            id = "cbse_10_sci_ch12_03",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Electricity",
            section = "12.3 Heating Effect and Electric Power",
            topic = "Joule's Law of Heating and Electric Power",
            conceptId = "concept_joules_heating",
            content = "Joule's Law of Heating: When electric current I passes through a conductor of resistance R for time t, heat energy produced is H = I^2 * R * t (or H = V * I * t = (V^2 / R) * t). Heat is proportional to square of current, resistance, and time. Electric Power (P) is the rate at which electrical energy is consumed: P = V * I = I^2 * R = V^2 / R (measured in Watts, W; 1 W = 1 J/s). Commercial unit of electrical energy is Kilowatt-hour (kWh, '1 Unit'): 1 kWh = 1000 W × 3600 s = 3.6 × 10^6 Joules (J). Electric fuses (low melting point alloy) protect appliances from power surges via Joule heating.",
            sourceCitation = "CBSE Science Class 10 Chapter 12 Section 12.3",
            keyFormula = "H = I^2 * R * t  •  P = V * I = I^2 * R = V^2 / R  •  1 kWh = 3.6 × 10^6 J",
            realWorldExample = "Electric irons, geysers, toasters, and tungsten filament lightbulbs heating up; safety electric fuse blowing during short circuit.",
            keywords = listOf("heating effect", "joules law", "power", "watt", "kilowatt-hour", "kwh", "electric energy", "fuse"),
            hindiSummary = "जूल का तापन नियम: H = I^2 * R * t। विद्युत शक्ति P = V * I = I^2 * R। व्यावसायिक ऊर्जा मात्रक: 1 kWh = 3.6 × 10^6 J।",
            odiaSummary = "ଜୁଲ୍‌ଙ୍କ ତାପନ ନିୟମ: H = I^2 * R * t। ବିଦ୍ୟୁତ ଶକ୍ତି P = V * I = I^2 * R। ୧ ୟୁନିଟ (kWh) = ୩.୬ × ୧୦^୬ ଜୁଲ୍।"
        ),

        // Chapter 4: Chemical Reactions and Equations
        CurriculumChunk(
            id = "cbse_10_sci_ch01_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Chemical Reactions and Equations",
            section = "1.1 Types of Chemical Reactions",
            topic = "Combination, Decomposition, Displacement, and Redox",
            conceptId = "concept_chemical_reactions",
            content = "A chemical reaction involves breaking and making chemical bonds between atoms to produce new substances. Law of Conservation of Mass dictates that equations must be balanced (atoms of each element equal on reactant and product sides). Types of Reactions: 1) Combination: Two or more reactants form one product: CaO + H2O → Ca(OH)2 (slaked lime). 2) Decomposition: Single reactant breaks down using heat (thermal: CaCO3 → CaO + CO2), electricity (electrolysis: 2H2O → 2H2 + O2), or light (photolysis: 2AgCl → 2Ag + Cl2). 3) Displacement: More reactive element displaces less reactive: Fe + CuSO4 (blue) → FeSO4 (green) + Cu. 4) Double Displacement (Precipitation): Exchange of ions: Na2SO4 + BaCl2 → BaSO4↓ (white ppt) + 2NaCl. 5) Redox: Simultaneous Oxidation (gain of oxygen / loss of electrons) and Reduction (loss of oxygen / gain of electrons).",
            sourceCitation = "CBSE Science Class 10 Chapter 1 Section 1.1",
            keyFormula = "Oxidation = Gain of O / Loss of H / Loss of e-  •  Reduction = Loss of O / Gain of H / Gain of e-",
            realWorldExample = "Rusting of iron (corrosion); digestion of food; baking soda reacting with vinegar; white washing walls with slaked lime.",
            keywords = listOf("chemical reaction", "balanced equation", "combination", "decomposition", "displacement", "redox", "oxidation", "reduction", "precipitation"),
            hindiSummary = "रासायनिक अभिक्रियाएं: संयोजन, वियोजन, विस्थापन, द्विविस्थापन और रेडॉक्स। द्रव्यमान संरक्षण के नियम से समीकरण संतुलित किए जाते हैं।",
            odiaSummary = "ରାସାୟନିକ ପ୍ରତିକ୍ରିୟା: ସଂଶ୍ଳେଷଣ, ବିଘଟନ, ବିସ୍ଥାପନ, ଦ୍ୱି-ବିସ୍ଥାପନ ଏବଂ ଜାରଣ-ବିଜାରଣ (Redox)।"
        ),

        // Chapter 5: Acids, Bases and Salts
        CurriculumChunk(
            id = "cbse_10_sci_ch02_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Acids, Bases and Salts",
            section = "2.1 Properties and pH Scale",
            topic = "Acids, Bases, Neutralization, and pH Scale",
            conceptId = "concept_acids_bases",
            content = "Acids produce hydrogen ions (H+ / H3O+) in aqueous solution, turn blue litmus red, and taste sour (e.g., HCl, H2SO4). Bases produce hydroxide ions (OH-) in aqueous solution, turn red litmus blue, and feel soapy (e.g., NaOH, Ca(OH)2). Neutralization Reaction: Acid + Base → Salt + Water (e.g., HCl + NaOH → NaCl + H2O). pH Scale measures H+ ion concentration from 0 to 14: Acidic (pH < 7), Neutral (pH = 7, pure water), Alkaline/Basic (pH > 7). Important salts: 1) Bleaching Powder: CaOCl2 (formed by chlorine on dry slaked lime). 2) Baking Soda: NaHCO3 (sodium hydrogen carbonate, antacid). 3) Washing Soda: Na2CO3·10H2O. 4) Plaster of Paris: CaSO4·1/2H2O (produced by heating gypsum CaSO4·2H2O at 373 K).",
            sourceCitation = "CBSE Science Class 10 Chapter 2 Section 2.1",
            keyFormula = "Acid + Base → Salt + Water  •  pH = -log[H+]  (Neutral = 7, Acid < 7, Base > 7)",
            realWorldExample = "Antacids (milk of magnesia / baking soda) neutralizing excess stomach acid; vinegar (acetic acid) in pickles; tooth decay when mouth pH < 5.5.",
            keywords = listOf("acid", "base", "salt", "ph scale", "neutralization", "litmus", "baking soda", "plaster of paris", "washing soda"),
            hindiSummary = "अम्ल, क्षार और लवण: अम्ल H+ आयन देते हैं (pH < 7), क्षार OH- आयन देते हैं (pH > 7)। उदासीनीकरण: अम्ल + क्षार → लवण + जल।",
            odiaSummary = "ଅମ୍ଳ, କ୍ଷାରକ ଓ ଲବଣ: ଅମ୍ଳ H+ ଆୟନ ଦିଏ (pH < ୭), କ୍ଷାରକ OH- ଆୟନ ଦିଏ (pH > ୭)। ପ୍ରଶମନ: ଅମ୍ଳ + କ୍ଷାରକ → ଲବଣ + ଜଳ।"
        ),

        // Chapter 6: Life Processes
        CurriculumChunk(
            id = "cbse_10_sci_ch06_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Science",
            chapter = "Life Processes",
            section = "6.1 Nutrition, Respiration, and Circulation",
            topic = "Life Processes in Organisms",
            conceptId = "concept_life_processes",
            content = "Life processes are essential maintenance functions required to sustain living organisms. 1) Photosynthesis (Autotrophic nutrition): 6CO2 + 12H2O + Chlorophyll + Sunlight → C6H12O6 (glucose) + 6O2 + 6H2O. Light energy converted to chemical energy in chloroplasts. 2) Respiration: Breakdown of glucose into pyruvate in cytoplasm. Aerobic respiration in mitochondria uses oxygen producing 36-38 ATP, CO2, and H2O. Anaerobic respiration occurs without oxygen: yeast produces ethanol + CO2, human muscle cramps produce lactic acid. 3) Human Circulation: Four-chambered heart (two atria, two ventricles) executes double circulation. Arteries carry oxygenated blood away from heart under high pressure; veins have valves preventing backflow. 4) Excretion: Kidneys filter nitrogenous waste (urea) via functional microscopic filtering units called Nephrons.",
            sourceCitation = "CBSE Science Class 10 Chapter 6 Section 6.1",
            keyFormula = "6CO2 + 6H2O → C6H12O6 + 6O2  •  Glucose → Pyruvate → CO2 + H2O + ATP (Mitochondria)",
            realWorldExample = "Plants producing oxygen during daylight; muscle soreness after sprinting due to lactic acid; artificial dialysis machines performing kidney functions.",
            keywords = listOf("photosynthesis", "respiration", "aerobic", "anaerobic", "heart", "circulation", "artery", "vein", "nephron", "kidney", "atp"),
            hindiSummary = "जैव प्रक्रम: प्रकाश संश्लेषण (भोजन निर्माण), श्वसन (ऊर्जा/ATP उत्पादन), मानव हृदय में दोहरा परिसंचरण, और वृक्क (नेफ्रॉन) द्वारा उत्सर्जन।",
            odiaSummary = "ଜୀବନ ପ୍ରକ୍ରିୟା: ଆଲୋକ ସଂଶ୍ଳେଷଣ, ଶ୍ୱସନ (ATP ଉତ୍ପାଦନ), ହୃତ୍‌ପିଣ୍ଡରେ ଦ୍ୱି-ପରିସଞ୍ଚାଳନ ଏବଂ ବୃକକ୍ (ନେଫ୍ରନ୍) ଦ୍ୱାରା ରେଚନ।"
        ),

        // Mathematics: Chapter 1: Real Numbers
        CurriculumChunk(
            id = "cbse_10_math_ch01_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Mathematics",
            chapter = "Real Numbers",
            section = "1.1 Fundamental Theorem of Arithmetic",
            topic = "Fundamental Theorem of Arithmetic and HCF/LCM",
            conceptId = "concept_real_numbers",
            content = "Fundamental Theorem of Arithmetic: Every composite number can be uniquely expressed (factorised) as a product of primes, apart from the order in which the prime factors occur. For any two positive integers a and b: HCF(a, b) * LCM(a, b) = a * b. HCF (Highest Common Factor) is the product of the smallest powers of each common prime factor. LCM (Least Common Multiple) is the product of the greatest powers of each prime factor involved in the numbers. Real numbers encompass rational numbers (p/q, terminating or non-terminating repeating) and irrational numbers (non-terminating non-repeating decimals, e.g., √2, √3, π).",
            sourceCitation = "CBSE Mathematics Class 10 Chapter 1 Section 1.1",
            keyFormula = "HCF(a, b) * LCM(a, b) = a * b  •  Euclid's Lemma: a = b*q + r (0 ≤ r < b)",
            realWorldExample = "Finding synchronized flashing intervals of traffic lights (LCM); tiling floors with maximum sized square tiles (HCF).",
            keywords = listOf("real numbers", "hcf", "lcm", "prime factorisation", "composite number", "fundamental theorem of arithmetic", "irrational"),
            hindiSummary = "अंकगणित की आधारभूत प्रमेय: प्रत्येक भाज्य संख्या को अभाज्य संख्याओं के गुणनफल के रूप में लिखा जा सकता है। HCF * LCM = a * b।",
            odiaSummary = "ପାଟିଗଣିତର ମୌଳିକ ପ୍ରମେୟ: ପ୍ରତ୍ୟେକ ଯୌଗିକ ସଂଖ୍ୟାକୁ ମୌଳିକ ଗୁଣନୀୟକରେ ପ୍ରକାଶ କରାଯାଏ। HCF * LCM = a * b।"
        ),

        // Mathematics: Chapter 2 & 4: Polynomials and Quadratic Equations
        CurriculumChunk(
            id = "cbse_10_math_ch04_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Mathematics",
            chapter = "Quadratic Equations",
            section = "4.1 Quadratic Formula and Nature of Roots",
            topic = "Quadratic Equations and Nature of Roots",
            conceptId = "concept_quadratics",
            content = "A quadratic equation in variable x is an equation of the standard form ax^2 + bx + c = 0, where a ≠ 0. The solutions are roots (zeroes). Quadratic Formula (Sridharacharya Formula): x = [-b ± √(b^2 - 4ac)] / (2a). The discriminant D = b^2 - 4ac determines the nature of the roots: 1) If D > 0: Two distinct real roots. 2) If D = 0: Two equal real roots (x = -b / (2a)). 3) If D < 0: No real roots (roots are complex/imaginary). For zeroes α and β: Sum of roots α + β = -b/a; Product of roots α * β = c/a.",
            sourceCitation = "CBSE Mathematics Class 10 Chapter 4 Section 4.1",
            keyFormula = "x = [-b ± √(b^2 - 4ac)] / (2a)  •  D = b^2 - 4ac  •  α + β = -b/a  •  α*β = c/a",
            realWorldExample = "Trajectory of an artillery projectile or basketball shot (parabola); determining dimensions of rectangular sports fields.",
            keywords = listOf("quadratic equation", "roots", "discriminant", "quadratic formula", "parabola", "sum of roots", "product of roots"),
            hindiSummary = "द्विघात समीकरण: ax^2 + bx + c = 0। विविक्तकर D = b^2 - 4ac। श्रीधराचार्य सूत्र: x = [-b ± √D] / (2a)। मूलों का योग = -b/a।",
            odiaSummary = "ଦ୍ୱିଘାତ ସମୀକରଣ: ax^2 + bx + c = 0। ପ୍ରଭେଦକ D = b^2 - 4ac। ମୂଳ x = [-b ± √D] / (2a)। ମୂଳଦ୍ୱୟର ଯୋଗଫଳ = -b/a।"
        ),

        // Mathematics: Chapter 3: Pair of Linear Equations
        CurriculumChunk(
            id = "cbse_10_math_ch03_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Mathematics",
            chapter = "Pair of Linear Equations in Two Variables",
            section = "3.1 Graphical and Algebraic Solutions",
            topic = "Linear Systems and Consistency Conditions",
            conceptId = "concept_linear_equations",
            content = "A pair of linear equations in two variables: a1*x + b1*y + c1 = 0 and a2*x + b2*y + c2 = 0. Consistency conditions: 1) a1/a2 ≠ b1/b2: Lines intersect at a single point; system has a Unique Solution and is Consistent. 2) a1/a2 = b1/b2 = c1/c2: Lines are coincident (overlapping); system has Infinitely Many Solutions and is Consistent (dependent). 3) a1/a2 = b1/b2 ≠ c1/c2: Lines are parallel; system has No Solution and is Inconsistent. Algebraic solution methods include Substitution, Elimination, and Cross-Multiplication.",
            sourceCitation = "CBSE Mathematics Class 10 Chapter 3 Section 3.1",
            keyFormula = "Unique: a1/a2 ≠ b1/b2  •  Infinitely Many: a1/a2 = b1/b2 = c1/c2  •  No Solution: a1/a2 = b1/b2 ≠ c1/c2",
            realWorldExample = "Determining break-even point for production costs and revenue; calculating ages of father and son from word problems.",
            keywords = listOf("linear equations", "intersecting lines", "parallel lines", "coincident", "unique solution", "elimination", "substitution"),
            hindiSummary = "रैखिक समीकरण युग्म: a1/a2 ≠ b1/b2 (अद्वितीय हल), a1/a2 = b1/b2 = c1/c2 (अनेक हल), a1/a2 = b1/b2 ≠ c1/c2 (कोई हल नहीं)।",
            odiaSummary = "ଯୁଗ୍ମ ରୈଖିକ ସମୀକରଣ: a1/a2 ≠ b1/b2 (ଅନନ୍ୟ ସମାଧାନ), a1/a2 = b1/b2 = c1/c2 (ଅସଂଖ୍ୟ ସମାଧାନ), a1/a2 = b1/b2 ≠ c1/c2 (ସମାଧାନ ନାହିଁ)।"
        ),

        // Mathematics: Chapter 5: Arithmetic Progressions
        CurriculumChunk(
            id = "cbse_10_math_ch05_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Mathematics",
            chapter = "Arithmetic Progressions",
            section = "5.1 nth Term and Sum of AP",
            topic = "Arithmetic Progressions (AP)",
            conceptId = "concept_ap",
            content = "An Arithmetic Progression (AP) is a sequence of numbers in which each term is obtained by adding a fixed number (common difference d) to the preceding term, with initial term a. Common difference: d = a_n - a_(n-1). The n-th term of an AP is given by: a_n = a + (n - 1) * d. Sum of first n terms of an AP: S_n = (n / 2) * [2a + (n - 1) * d] = (n / 2) * [a + l], where l is the last term (a_n). If three numbers a, b, c are in AP, then 2b = a + c (b is the arithmetic mean).",
            sourceCitation = "CBSE Mathematics Class 10 Chapter 5 Section 5.1",
            keyFormula = "a_n = a + (n - 1)*d  •  S_n = (n/2)*[2a + (n - 1)*d] = (n/2)*[a + l]",
            realWorldExample = "Salary increments every consecutive year; ladder rungs decreasing uniformly in length; calculating savings deposits over months.",
            keywords = listOf("arithmetic progression", "ap", "common difference", "nth term", "sum of ap", "series"),
            hindiSummary = "समांतर श्रेढ़ी (AP): n-वां पद a_n = a + (n - 1)*d। n पदों का योग S_n = (n/2)*[2a + (n - 1)*d]।",
            odiaSummary = "ସମାନ୍ତର ପ୍ରଗତି (AP): n-ତମ ପଦ a_n = a + (n - 1)*d। n ପଦର ସମଷ୍ଟି S_n = (n/2)*[2a + (n - 1)*d]। "
        ),

        // Mathematics: Chapter 8: Trigonometry
        CurriculumChunk(
            id = "cbse_10_math_ch08_01",
            board = "CBSE",
            classLevel = "Class 10",
            subject = "Mathematics",
            chapter = "Introduction to Trigonometry",
            section = "8.1 Trigonometric Ratios and Identities",
            topic = "Trigonometric Ratios and Fundamental Identities",
            conceptId = "concept_trigonometry",
            content = "In a right-angled triangle with acute angle θ: sin(θ) = Opposite / Hypotenuse, cos(θ) = Adjacent / Hypotenuse, tan(θ) = Opposite / Adjacent = sin(θ) / cos(θ). Reciprocal ratios: cosec(θ) = 1/sin(θ), sec(θ) = 1/cos(θ), cot(θ) = 1/tan(θ). Standard angle values: sin(30°) = 1/2, sin(45°) = 1/√2, sin(60°) = √3/2, sin(90°) = 1; cos(30°) = √3/2, cos(45°) = 1/√2, cos(60°) = 1/2, cos(90°) = 0; tan(45°) = 1. Three Fundamental Trigonometric Identities: 1) sin^2(θ) + cos^2(θ) = 1; 2) 1 + tan^2(θ) = sec^2(θ); 3) 1 + cot^2(θ) = cosec^2(θ).",
            sourceCitation = "CBSE Mathematics Class 10 Chapter 8 Section 8.1",
            keyFormula = "sin^2(θ) + cos^2(θ) = 1  •  1 + tan^2(θ) = sec^2(θ)  •  1 + cot^2(θ) = cosec^2(θ)",
            realWorldExample = "Measuring heights of towers, mountains, and trees using angles of elevation (clinometer); GPS triangulation.",
            keywords = listOf("trigonometry", "sin", "cos", "tan", "cosec", "sec", "cot", "trigonometric identities", "right triangle"),
            hindiSummary = "त्रिकोणमिति: sin^2(θ) + cos^2(θ) = 1, 1 + tan^2(θ) = sec^2(θ)। मानक मान: sin(30°) = 1/2, sin(90°) = 1, tan(45°) = 1।",
            odiaSummary = "ତ୍ରିକୋଣମିତି: sin^2(θ) + cos^2(θ) = 1, 1 + tan^2(θ) = sec^2(θ)। ମାନ: sin(୩୦°) = ୧/୨, tan(୪୫°) = ୧।"
        ),

        // Physics foundation: Newton's Laws of Motion
        CurriculumChunk(
            id = "cbse_9_sci_ch09_01",
            board = "CBSE",
            classLevel = "Class 9",
            subject = "Science",
            chapter = "Force and Laws of Motion",
            section = "9.3 Newton's Laws of Motion",
            topic = "Newton's Three Laws of Motion",
            conceptId = "concept_newtons_laws",
            content = "Newton's First Law states that an object remains at rest or continues moving with uniform velocity in a straight line unless acted on by an external unbalanced force; this is the law of inertia. Newton's Second Law states that the net force on an object equals the rate of change of its momentum; for constant mass, F = m × a. Newton's Third Law states that for every action force there is an equal and opposite reaction force. The two forces act simultaneously on different objects, so they do not cancel each other on one object. For example, when you push the ground backward while walking, the ground pushes you forward.",
            sourceCitation = "CBSE Science Class 9 Chapter 9 Section 9.3",
            keyFormula = "F = m × a  •  Action force = -Reaction force",
            realWorldExample = "Walking, swimming, recoil of a gun, and rocket propulsion demonstrate action-reaction pairs.",
            keywords = listOf("newton", "newtons laws", "newton's laws", "first law", "second law", "third law", "third", "force", "inertia", "momentum", "action reaction", "motion"),
            hindiSummary = "न्यूटन का तीसरा नियम: प्रत्येक क्रिया के बराबर और विपरीत प्रतिक्रिया होती है। दोनों बल अलग-अलग वस्तुओं पर लगते हैं।",
            odiaSummary = "ନ୍ୟୁଟନଙ୍କ ତୃତୀୟ ନିୟମ: ପ୍ରତ୍ୟେକ କ୍ରିୟାର ସମାନ ଓ ବିପରୀତ ପ୍ରତିକ୍ରିୟା ଥାଏ। ଦୁଇଟି ବଳ ଭିନ୍ନ ବସ୍ତୁ ଉପରେ କାର୍ଯ୍ୟ କରେ।"
        )
    )
}
